local vehicles = lib.callback.await('ars_tuning:retreiveEsxVehicles')

return vehicles

-- local vehicles = {
--     ['adder'] = {
--         name = 'Adder',
--         price = '765000'
--     },
--     ['akuma'] = {
--         name = 'Akuma',
--         price = '22000'
--     },
--     ['alpha'] = {
--         name = 'Alpha',
--         price = '32000'
--     },
--     ['aqv'] = {
--         name = 'Alpha romeo giulia',
--         price = '413000'
--     },
--     ['avarus'] = {
--         name = 'Avarus',
--         price = '19000'
--     },
--     ['bagger'] = {
--         name = 'Bagger',
--         price = '7000'
--     },
--     ['baller2'] = {
--         name = 'Baller',
--         price = '65000'
--     },
--     ['baller3'] = {
--         name = 'Baller Sport',
--         price = '70000'
--     },
--     ['bati'] = {
--         name = 'Bati 801',
--         price = '22000'
--     },
--     ['bati2'] = {
--         name = 'Bati 801RR',
--         price = '23000'
--     },
--     ['bf400'] = {
--         name = 'BF400',
--         price = '35000'
--     },
--     ['bifta'] = {
--         name = 'Bifta',
--         price = '17000'
--     },
--     ['bison'] = {
--         name = 'Bison',
--         price = '45000'
--     },
--     ['blade'] = {
--         name = 'Blade',
--         price = '15000'
--     },
--     ['blazer'] = {
--         name = 'Blazer',
--         price = '6500'
--     },
--     ['blazer4'] = {
--         name = 'Blazer Sport',
--         price = '8500'
--     },
--     ['blazer5'] = {
--         name = 'Blazer 5',
--         price = '1755600'
--     },
--     ['blista'] = {
--         name = 'Blista',
--         price = '8000'
--     },
--     ['bmci'] = {
--         name = 'BMW M5',
--         price = '465000'
--     },
--     ['brawler'] = {
--         name = 'Brawler',
--         price = '45000'
--     },
--     ['brioso'] = {
--         name = 'Brioso R/A',
--         price = '18000'
--     },
--     ['burrito3'] = {
--         name = 'Burrito',
--         price = '19000'
--     },
--     ['carbonrs'] = {
--         name = 'Carbon RS',
--         price = '32000'
--     },
--     ['cheetah'] = {
--         name = 'Cheetah',
--         price = '375000'
--     },
--     ['chimera'] = {
--         name = 'Chimera',
--         price = '17000'
--     },
--     ['cognoscenti'] = {
--         name = 'Cognoscenti',
--         price = '55000'
--     },
--     ['contender'] = {
--         name = 'Contender',
--         price = '70000'
--     },
--     ['dominator'] = {
--         name = 'Dominator',
--         price = '54500'
--     },
--     ['dubsta2'] = {
--         name = 'Dubsta Luxuary',
--         price = '60000'
--     },
--     ['dubsta3'] = {
--         name = 'Bubsta 6x6',
--         price = '120000'
--     },
--     ['elegy2'] = {
--         name = 'Elegy',
--         price = '38500'
--     },
--     ['entityxf'] = {
--         name = 'Entity XF',
--         price = '425000'
--     },
--     ['exemplar'] = {
--         name = 'Exemplar',
--         price = '32000'
--     },
--     ['f620'] = {
--         name = 'F620',
--         price = '40000'
--     },
--     ['faggio'] = {
--         name = 'Faggio',
--         price = '4000'
--     },
--     ['felon'] = {
--         name = 'Felon',
--         price = '42000'
--     },
--     ['felon2'] = {
--         name = 'Felon GT',
--         price = '55000'
--     },
--     ['fmj'] = {
--         name = 'FMJ',
--         price = '440000'
--     },
--     ['furoregt'] = {
--         name = 'Furore GT',
--         price = '85000'
--     },
--     ['fusilade'] = {
--         name = 'Fusilade',
--         price = '50000'
--     },
--     ['guardian'] = {
--         name = 'Guardian',
--         price = '45000'
--     },
--     ['hustler'] = {
--         name = 'Hustler',
--         price = '625000'
--     },
--     ['infernus'] = {
--         name = 'Infernus',
--         price = '380000'
--     },
--     ['issi2'] = {
--         name = 'Issi',
--         price = '10000'
--     },
--     ['jackal'] = {
--         name = 'Jackal',
--         price = '38000'
--     },
--     ['kamacho'] = {
--         name = 'Kamacho',
--         price = '175000'
--     },
--     ['khamelion'] = {
--         name = 'Khamelion',
--         price = '38000'
--     },
--     ['kuruma'] = {
--         name = 'Kuruma',
--         price = '90000'
--     },
--     ['landstalker'] = {
--         name = 'Landstalker',
--         price = '35000'
--     },
--     ['le7b'] = {
--         name = 'RE-7B',
--         price = '325000'
--     },
--     ['lynx'] = {
--         name = 'Lynx',
--         price = '40000'
--     },
--     ['mamba'] = {
--         name = 'Mamba',
--         price = '70000'
--     },
--     ['manana'] = {
--         name = 'Manana',
--         price = '12800'
--     },
--     ['massacro'] = {
--         name = 'Massacro',
--         price = '65000'
--     },
--     ['massacro2'] = {
--         name = 'Massacro(Racecar)',
--         price = '130000'
--     },
--     ['mesa3'] = {
--         name = 'Mesa',
--         price = '85000'
--     },
--     ['monster'] = {
--         name = 'The Liberator',
--         price = '210000'
--     },
--     ['neon'] = {
--         name = 'Neon',
--         price = '450000'
--     },
--     ['nightblade'] = {
--         name = 'Nightblade',
--         price = '35000'
--     },
--     ['nightshade'] = {
--         name = 'Nightshade',
--         price = '65000'
--     },
--     ['omnis'] = {
--         name = 'Omnis',
--         price = '35000'
--     },
--     ['oracle2'] = {
--         name = 'Oracle XS',
--         price = '35000'
--     },
--     ['panto'] = {
--         name = 'Panto',
--         price = '10000'
--     },
--     ['pariah'] = {
--         name = 'Pariah',
--         price = '235000'
--     },
--     ['prototipo'] = {
--         name = 'X80 Proto',
--         price = '65000'
--     },
--     ['raptor150'] = {
--         name = 'Raptor',
--         price = '380000'
--     },
--     ['reaper'] = {
--         name = 'Reaper',
--         price = '230000'
--     },
--     ['riata'] = {
--         name = 'Riata',
--         price = '380000'
--     },
--     ['rumpo'] = {
--         name = 'Rumpo',
--         price = '27000'
--     },
--     ['rumpo3'] = {
--         name = 'Rumpo Trail',
--         price = '68124'
--     },
--     ['sanchez'] = {
--         name = 'Sanchez',
--         price = '22000'
--     },
--     ['sanctus'] = {
--         name = 'Sanctus',
--         price = '25000'
--     },
--     ['sandking'] = {
--         name = 'Sandking',
--         price = '55000'
--     },
--     ['sc1'] = {
--         name = 'SC 1',
--         price = '329000'
--     },
--     ['senna'] = {
--         name = 'Senna',
--         price = '857000'
--     },
--     ['seven70'] = {
--         name = 'Seven 70',
--         price = '39500'
--     },
--     ['sheava'] = {
--         name = 'ETR1',
--         price = '220000'
--     },
--     ['Sultan RS'] = {
--         name = 'sultanrs',
--         price = '65000'
--     },
--     ['t20'] = {
--         name = 'T 20',
--         price = '420000'
--     },
--     ['tempesta'] = {
--         name = 'Tempesta',
--         price = '350000'
--     },
--     ['tropos'] = {
--         name = 'Tropos',
--         price = '40000'
--     },
--     ['coquette'] = {
--         name = 'Coquette',
--         price = '65000'
--     },
--     ['turismor'] = {
--         name = 'Turismo R',
--         price = '220000'
--     },
--     ['vacca'] = {
--         name = 'Vacca',
--         price = '170000'
--     },
--     ['verlierer2'] = {
--         name = 'Verlierer',
--         price = '70000'
--     },
--     ['visione'] = {
--         name = 'Visione',
--         price = '780000'
--     },
--     ['voltic'] = {
--         name = 'Voltic',
--         price = '90000'
--     },
--     ['voodoo'] = {
--         name = 'Voodoo',
--         price = '21000'
--     },
--     ['vortex'] = {
--         name = 'Vortex',
--         price = '9800'
--     },
--     ['windsor'] = {
--         name = 'Windsor',
--         price = '95000'
--     },
--     ['windsor2'] = {
--         name = 'Windsor Drop',
--         price = '125000'
--     },
--     ['zentorno'] = {
--         name = 'zentorno',
--         price = '700000'
--     },
-- }


-- return vehicles
